export const FETCHING_COINS = 'FETCHING_COINS'
export const FETCHING_COINS_SUCCESS = 'FETCHING_COINS_SUCCESS'
export const FETCHING_COINS_FAILURE = 'FETCHING_COINS_FAILURE'

export const FETCHING_COIN_INFO_SUCCESS = 'FETCHING_COIN_INFO_SUCCESS'

export const FETCHING_COIN_HISTORY_SUCCESS = 'FETCHING_COIN_HISTORY_SUCCESS'

export const CHANGE_COIN_HISTORY_SUCCESS = 'CHANGE_COIN_HISTORY_SUCCESS'
