export const FETCHING_COINS = 'FETCHING_COINS'
export const FETCHING_COINS_SUCCESS = 'FETCHING_COINS_SUCCESS'
export const FETCHING_COINS_FAILURE = 'FETCHING_COINS_FAILURE'

export const FETCHING_COIN_INFO_SUCCESS = 'FETCHING_COIN_INFO_SUCCESS'
export const FETCHING_COIN_HISTORY = 'FETCHING_COIN_HISTORY'

export const FETCHING_COIN_LIST = 'FETCHING_COIN_LIST'

export const FETCHING_COIN_HISTORY_SUCCESS = 'FETCHING_COIN_HISTORY_SUCCESS'

export const CHANGE_COIN_HISTORY_SUCCESS = 'CHANGE_COIN_HISTORY_SUCCESS'

export const ADD_COIN = 'ADD_COIN'
export const REMOVE_COIN = 'REMOVE_COIN'
export const VIEW_COIN = 'VIEW_COIN'
export const SEARCH_COIN = 'SEARCH_COIN'
export const HOME = 'HOME'
export const COIN = 'COIN'
export const SEARCH = 'SEARCH'

export const MARKETCAP = 'MARKETCAP'
export const FETCHING_MARKETCAP = 'FETCHING_MARKETCAP'

export const COINLIST = 'COINLIST'
export const USERCOINLIST = 'USERCOINLIST'
export const FETCHING_COIN_HISTORY_FAILURE = 'FETCHING_COIN_HISTORY_FAILURE'

export const FORCE_REHYDRATE = 'FORCE_REHYDRATE'
